stages:
  - test
  - deploy

run_tests:
  stage: test
  image: maven:3.9.9-amazoncorretto-17
  script:
    - mvn test

deploy:
  stage: deploy
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY root@18.153.231.91
    - mvn build