stages:
  - test
  - build
  - deploy

run_tests:
  stage: test
  image: maven:3.9.9-amazoncorretto-17
  script:
    - mvn test

build:
  stage: build
  script:
    - ng build
    - ssh -i $SSH_KEY ubuntu@circles.kriszti.app

deploy:
  stage: deploy
  script:
    # Kill running process on server
    - ssh -i $SSH_KEY ubuntu@circles.kriszti.app "~/shutdown.sh ~/circles-app-1.0-SNAPSHOT.jar"
    # Copy backend files
    - scp -i $SSH_KEY -r ./target/circles-app-1.0-SNAPSHOT.jar ubuntu@$circles.kriszti.app:~
    # Start backend server
    - ssh -i $SSH_KEY ubuntu@$circles.kriszti.app "~/startup.sh ~/circles-app-1.0-SNAPSHOT.jar"
    
    